apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "smithery.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "smithery.labels" . | nindent 4 }}
rules:
- apiGroups:
  - widgets.templates.krateo.io
  resources:
  - "*"
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - secrets
  verbs:
  - get
  - list