apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smithery.fullname" . }}
  labels:
  {{- include "smithery.labels" . | nindent 4 }}
data:
  PORT: "{{ .Values.service.port }}"
  AUTHN_NAMESPACE: {{ .Release.Namespace }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}