apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smithery.fullname" . }}
  labels:
  {{- include "smithery.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}